# Generated by Django 5.1.1 on 2025-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'All'), ('2', 'Completed'), ('3', 'Active'), ('4', 'Has due date')], default='3', max_length=1),
        ),
    ]
